[2024-01-20T02:32:04.600+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/usr/local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 421, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark ./spark/silver_spark.py. Error code is: 1.
[2024-01-20T02:32:04.629+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task silver_trusted_transformacao (Cannot execute: spark-submit --master yarn --name arrow-spark ./spark/silver_spark.py. Error code is: 1.; 1113)
